crds:
  install: true
global:
  image:
    repository: "quay.io/argoproj/argocd"
  revisionHistoryLimit: 2
  securityContext:
    fsGroup: 999
  affinity:
    podAntiAffinity: "none"
  networkPolicy:
    create: true
dex:
  image:
    repository: "ghcr.io/dexidp/dex"
  metrics:
    enabled: true
  initContainers:
    - name: fetch-ca
      image: curlimages/curl:8.8.0
      command: ["sh", "-c"]
      args:
        - |
          echo "Fetching Teleport SAML metadata..."
          cert=$(curl -s https://localhost/enterprise/saml-idp/metadata \
            | tr -d '\n' \
            | sed -n 's/.*<KeyDescriptor use="signing">.*<X509Certificate[^>]*>\([^<]*\)<\/X509Certificate>.*/\1/p')
          if [ -z "$cert" ]; then
            echo "No certificate found. Check XML structure." >&2
            exit 1
          else
            echo -e "-----BEGIN CERTIFICATE-----\n$cert\n-----END CERTIFICATE-----" > /etc/dex/teleport-ca.pem
            echo "Successfully fetched certificate."
          fi
      volumeMounts:
        - name: teleport-ca
          mountPath: /etc/dex
  volumeMounts:
    - name: teleport-ca
      mountPath: /etc/dex
  volumes:
    - name: teleport-ca
      emptyDir: {}
redis:
  image:
    repository: "docker.io/library/redis"
configs:
  secret:
    createSecret: true
  params:
    server.insecure: true
  rbac:
    policy.default: role:readonly
    policy.csv: |
      g, access, role:admin
  cm:
    # application.resourceTrackingMethod: "annotation"
    kustomize.buildOptions: --enable-helm
    url: https://argocd-server-http-argocd-test-cluster.teleport.localhost
    dex.config: |
      connectors:
        - type: saml
          id: argocd
          name: SSO
          config:
            ssoURL: https://teleport.localhost/enterprise/saml-idp/sso
            ca: /etc/dex/teleport-ca.pem
            redirectURI: https://argocd-server-http-argocd-test-cluster.teleport.localhost/api/dex/callback
            entityIssuer: https://argocd-server-http-argocd-test-cluster.teleport.localhost/api/dex/callback
            usernameAttr: urn:oid:0.9.2342.19200300.100.1.1
            emailAttr: urn:oid:0.9.2342.19200300.100.1.1
            groupsAttr: urn:oid:1.3.6.1.4.1.5923.1.1.1.1
            nameIDPolicyFormat: transient
    resource.exclusions: |
      ### Network resources created by the Kubernetes control plane and excluded to reduce the number of watched events and UI clutter
      - apiGroups:
        - ''
        - discovery.k8s.io
        kinds:
        - Endpoints
        - EndpointSlice
      ### Internal Kubernetes resources excluded reduce the number of watched events
      - apiGroups:
        - coordination.k8s.io
        kinds:
        - Lease
      ### Internal Kubernetes Authz/Authn resources excluded reduce the number of watched events
      - apiGroups:
        - authentication.k8s.io
        - authorization.k8s.io
        kinds:
        - SelfSubjectReview
        - TokenReview
        - LocalSubjectAccessReview
        - SelfSubjectAccessReview
        - SelfSubjectRulesReview
        - SubjectAccessReview
      ### Intermediate Certificate Request excluded reduce the number of watched events
      - apiGroups:
        - certificates.k8s.io
        kinds:
        - CertificateSigningRequest
      - apiGroups:
        - cert-manager.io
        kinds:
        - CertificateRequest
      ### Cilium internal resources excluded reduce the number of watched events and UI Clutter
      - apiGroups:
        - cilium.io
        kinds:
        - CiliumIdentity
        - CiliumEndpoint
        - CiliumEndpointSlice
      ### Kyverno intermediate and reporting resources excluded reduce the number of watched events and improve performance
      - apiGroups:
        - kyverno.io
        - reports.kyverno.io
        - wgpolicyk8s.io
        kinds:
        - PolicyReport
        - ClusterPolicyReport
        - EphemeralReport
        - ClusterEphemeralReport
        - AdmissionReport
        - ClusterAdmissionReport
        - BackgroundScanReport
        - ClusterBackgroundScanReport
        - UpdateRequest
      - apiGroups:
        - "*"
        kinds:
        - ProviderConfigUsage