apiVersion: resources.teleport.dev/v1
kind: TeleportRoleV7
metadata:
  name: admin
  namespace: teleport-cluster
spec:
  allow:
    kubernetes_groups:
    - system:masters
    kubernetes_labels:
      '*': '*'
    kubernetes_resources:
    - kind: '*'
      namespace: '*'
      name: '*'
      verbs:
      - '*'
